# -*- coding: utf-8 -*-
"""论文第三轮修订（2026-10-09 晚，用户：「按照你的想法来」）：压篇幅与引言定位。
- 删去第 6.3 节（proper 超几何多重和：定义 6.12、条件 (N1)(N2)、定理 6.13、引理 6.14-6.16、命题 6.17 与其讨论）。
  理由：(N1)(N2) 偏人为、这一节约 3 页；结论（报告 T2.7'）与 Lean 定理 partialSum_P_not_hypergeometric 仍在仓库。
  连带：引言定理 C 去掉第 (4) 条与对 thm:multisum 的引用；第 6 节开头一句；相关工作里「是第 6.3 节的出发点」一句；
  第 9 节表 5 的命题 6.17 一行、partialSum_P_not_hypergeometric 那句与「Not formalized」里的「apart from 命题 6.17」。
  第 6 节之后的编号不变（第 7 节起重新计数）。
- 引言「Main results」开头加一段定位：U_k(m) 是 Λ_k 的多重链数，布尔格对应 (m+1)^k、q!S(k,q) 与 Euler 多项式；
  定理 D(3)、E、F 分别对应 Stirling 数的零化子（Kauers 例 5）、对角线多项式（Gessel-Stanley）与 Euler 多项式的实根性，
  定理 D(4) 与 h_k 大于 1 的零点是类比失效之处。定理 F 之后那段相应缩短（Λ_k 已在前面定义）。
- 没有删注记 3.3 的数值段（check_paper_numbers 的 P24 核对它，删了只省几行）、注记 3.5、第 6.2 节的证书细节与附录 A
  （附录 A 是审稿人不看仓库也能核对形式化陈述是否忠实的地方）。
每处替换断言原文出现一次；按字节读写（paper/main.tex 是 LF）。

用法（在任务 C 根目录）：py -3.14 code/main_extra/report_patches/patch_paper_2026-10-09_trim.py [tex 路径]
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))

FRAMING = (
    r'Let $\Lambda_k\subseteq\{0,1\}^k$ be the set of binary words of length $k$ that avoid $001$ and $010$, ordered '
    r'componentwise. Then $U_k(m)$ is the number of multichains of length $m$ in $\Lambda_k$ (Proposition~\ref{prop:multichain}), '
    r'and the triangle $N(k,q)$ and the polynomials $h_k$ introduced below count chains in $\Lambda_k$ and are $h$-polynomials '
    r'of order complexes; for the whole Boolean lattice $\{0,1\}^k$ the same constructions give $(m+1)^k$, the numbers '
    r'$q!\stirling{k}{q}$ and the Eulerian polynomials (Remark~\ref{rem:chains}). Accordingly, several of our results parallel '
    r'classical facts: the annihilator of the Stirling numbers $\stirling{n}{k}$ is generated by their triangular recurrence '
    r'\cite[Example~5]{Kauers07}, the near-diagonals $\stirling{k}{k-d}$ are polynomials in $k$ \cite{GesselStanley}, and the '
    r'Eulerian polynomials are real-rooted \cite{Branden}; compare Theorems~\ref{thmD}(3), \ref{thmE} and~\ref{thmF}. '
    r'Theorem~\ref{thmD}(4) and the zeros of $h_k$ greater than $1$ (Theorem~\ref{thmF}) show where the analogy ends.' '\n\n'
)

REPS = [
    # --- 引言：Main results 开头的定位段
    (r'\subsection{Main results}' '\n' r'Throughout, $b_i(x)=1-x-ix^3$,',
     r'\subsection{Main results}' '\n' + FRAMING + r'Throughout, $b_i(x)=1-x-ix^3$,'),
    # --- 引言：定理 F 之后那段缩短
    (r'Let $\Lambda_k\subseteq\{0,1\}^k$ be the set of binary words of length $k$ that avoid $001$ and $010$, ordered '
     r'componentwise. Then $U_k(m)$ is the number of multichains of length $m$ in $\Lambda_k$ (Proposition~\ref{prop:multichain}), '
     r'$N(k,q)$ is the number of chains with $q-1$ elements in $\Lambda_k$ without its least and greatest element, and $h_k$ is the '
     r'$h$-polynomial of the corresponding order complex; for the Boolean lattice $\{0,1\}^k$ the same constructions give '
     r'$(m+1)^k$, the numbers $q!\stirling{k}{q}$ and the Eulerian polynomials (Remark~\ref{rem:chains}). Theorem~\ref{thmF} is '
     r'thus a real-rootedness result for chain polynomials,',
     r'Since $N(k,q)$ is the number of chains with $q-1$ elements in $\Lambda_k$ without its least and greatest element '
     r'(Remark~\ref{rem:chains}), Theorem~\ref{thmF} is a real-rootedness result for chain polynomials,'),
    # --- 引言：定理 C 去掉第 (4) 条
    (r'\ref{thm:shapes}, \ref{thm:twofam} and~\ref{thm:multisum}]\label{thmC}',
     r'\ref{thm:shapes} and~\ref{thm:twofam}]\label{thmC}'),
    (r'\item $U_k(m)$ is not a finite multisum $\sum_{\vec j}T(k,m,\vec j)$ of a proper hypergeometric term $T$ that satisfies '
     r'the boundary conditions (N1) and (N2) of Section~\ref{sec:multisum}.' '\n', ''),
    # --- 相关工作
    (r' the holonomic approach to special function identities, including the fact that a proper hypergeometric term satisfies '
     r'a recurrence whose coefficients do not involve the summation variables \cite[Theorem~4.1]{WZ92}, which is the starting '
     r'point of Section~\ref{sec:multisum}.',
     r' the holonomic approach to special function identities.'),
    # --- 第 6 节开头
    (r' (Section~\ref{sec:single}); that it is not a sum of two such single sums for $m\ge2$ (Section~\ref{sec:twofam}); and '
     r'that it is not a multisum of a proper hypergeometric term satisfying the boundary conditions (N1) and (N2) of '
     r'Section~\ref{sec:multisum}.',
     r' (Section~\ref{sec:single}); and that it is not a sum of two such single sums for $m\ge2$ (Section~\ref{sec:twofam}).'),
    # --- 第 9 节
    (r'Proposition~\ref{prop:gosper} & \lean{partialSum\_P\_not\_hypergeometric}\\' '\n', ''),
    (r' In \lean{partialSum\_P\_not\_hypergeometric} the notion of hypergeometric term is slightly more general than in '
     r'Proposition~\ref{prop:gosper} ($q(m)T(m+1)=p(m)T(m)$ for large $m$ with $q\ne0$), so the formal statement is stronger.',
     ''),
    (r'Section~\ref{sec:short}, apart from Proposition~\ref{prop:gosper};', r'Section~\ref{sec:short};'),
    # --- 附录 A 开头的说明
    (r'(for instance the Lean versions of $b_i$, $P_m$, $W_m$ and $\rho_m$, of the spaces in Theorem~\ref{thm:ideal}(2), and '
     r'of hypergeometric terms in Proposition~\ref{prop:gosper})',
     r'(for instance the Lean versions of $b_i$, $P_m$, $W_m$ and $\rho_m$, and of the spaces in Theorem~\ref{thm:ideal}(2))'),
]

CUT_START = r'\subsection{Proper hypergeometric multisums}\label{sec:multisum}'
CUT_END = '% =====================================================================\n' + r'\section{The near-diagonal of the triangle}'


def main():
    if not sys.stdout.isatty():
        sys.stdout.reconfigure(encoding='utf-8')
    p = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'paper', 'main.tex')
    raw = open(p, 'rb').read()
    assert b'\r\n' not in raw
    s = raw.decode('utf-8')
    # 第 6.3 节整节删去
    assert s.count(CUT_START) == 1 and s.count(CUT_END) == 1
    a, b = s.index(CUT_START), s.index(CUT_END)
    assert a < b and s[a:b].count(r'\section{') == 0
    removed = s[a:b]
    s = s[:a] + s[b:]
    for old, new in REPS:
        c = s.count(old)
        assert c == 1, (c, old[:70])
        s = s.replace(old, new)
    for lab in ('sec:multisum', 'thm:multisum', 'prop:gosper', 'lem:WZ', '(N1)', '(N2)'):
        assert lab not in s, lab
    open(p, 'wb').write(s.encode('utf-8'))
    print('paper/main.tex: section 6.3 removed (%d bytes), %d edits' % (len(removed.encode('utf-8')), len(REPS)))


if __name__ == '__main__':
    main()
