# 第三次新颖性补查（2026-10-10，只读）：针对 10-09 修订后的论文第 5 节（N 的零化理想、二项式变换搬运）、第 6 节（求和形状的否定结果）、
# 第 8 节（h_k 实根性、链多项式）。10-07 的检索没有覆盖第 8 节：当时实根性还是猜想 B1，链多项式的表述是 10-09 才加的。
# 复用 lit_search.py 的请求、构造与解析函数（同样的限速：arXiv >= 3.2 s、Crossref >= 1 s、OpenAlex 约 0.4 s）和 cited_by.py 的 OpenAlex 前向引用取法。
# 原始返回存 data/lit/raw_recheck_2026-10-10/（已存在的文件不重取），汇总表 data/lit/recheck_2026-10-10.md 只由本地原始文件生成，离线可复现。
# 10-07 的数据与汇总表不动。不带邮箱、不登录、不发帖、不联系任何人；外发的只有下面这些通用关键词。
# 用法：py -3.14 code/novelty/recheck_2026-10-10.py run [--sources openalex,crossref,arxiv]
#       py -3.14 code/novelty/recheck_2026-10-10.py report
import argparse, json, os, sys, time, urllib.parse

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import lit_search as LS  # noqa: E402
import cited_by as CB  # noqa: E402

ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
RAW = os.path.join(ROOT, "data", "lit", "raw_recheck_2026-10-10")
REPORT = os.path.join(ROOT, "data", "lit", "recheck_2026-10-10.md")
Q = LS.Q

QUERIES = [
    # ---- 第 8 节：h_k 实根、链多项式、序复形 ----
    Q("rr01", "§8 链多项式", "chain polynomial real-rooted poset", 'abs:"chain polynomial" AND abs:real'),
    Q("rr02", "§8 链多项式", "chain polynomials of posets with only real zeros", 'abs:"chain polynomials"'),
    Q("rr03", "§8 序复形", "h-polynomial of the order complex of a poset real-rooted", 'abs:"order complex" AND abs:"real-rooted"'),
    Q("rr04", "§8 多重链", "multichain enumeration Eulerian polynomial analogue poset real roots", 'abs:multichains AND abs:"real roots"'),
    Q("rr05", "§8 对象", "subposet of the Boolean lattice binary words avoiding patterns chains", 'abs:"Boolean lattice" AND abs:words AND abs:avoiding'),
    Q("rr06", "§8 方法", "row polynomials of a Stirling-type triangle real zeros interlacing recurrence", 'abs:interlacing AND abs:Stirling AND abs:zeros'),
    Q("rr07", "§8 零点位置", "real-rooted polynomial zeros greater than one sign changes of coefficients", 'abs:"real-rooted" AND abs:"sign changes"'),
    Q("rr08", "§8 TN 方法", "totally nonnegative matrices chain enumeration zeros of polynomials", 'abs:"totally nonnegative" AND abs:chain'),
    Q("rr09", "§8 Stanley 猜想", "chain polynomial (3+1)-free posets real roots Stanley conjecture", 'abs:"chain polynomial" AND abs:"free"'),
    Q("rr10", "§8 方法", "real-rootedness polynomials defined by a recurrence interlacing preserving linear operators", 'abs:"real-rootedness" AND abs:recurrence AND abs:interlacing'),
    Q("rr11", "§8 对象", "zeta polynomial of a poset real zeros", 'abs:"zeta polynomial" AND abs:zeros'),
    Q("rr12", "§8 对数凹", "log-concavity rows of a combinatorial triangle number of words using exactly q letters", 'abs:"log-concave" AND abs:triangle AND abs:words'),
    # ---- 第 5 节：零化理想、二项式变换、收缩 ----
    Q("id01", "§5 N 的理想", "annihilator of a triangular array binomial transform Ore algebra left ideal", 'abs:annihilator AND abs:"binomial transform"'),
    Q("id02", "§5 Stirling-like", "Stirling-like sequences annihilating operators", 'abs:"Stirling-like"'),
    Q("id03", "§5 收缩", "contraction of Ore ideals polynomial coefficients saturation", 'abs:contraction AND abs:Ore'),
    Q("id04", "§5 全部递推", "all recurrences of a bivariate sequence generated by one operator dimension of recurrences of bounded order and degree", 'abs:recurrences AND abs:"left ideal"'),
    # ---- 第 6 节：求和形状的否定结果 ----
    Q("ob01", "§6 单和形状", "sequence not expressible as a single sum of binomial coefficients shape of summation formula", 'abs:"single sum" AND abs:binomial AND abs:recurrence'),
    Q("ob02", "§6 单和形状", "C-finite sequence representation as sum of binomial coefficients times exponential", 'abs:"C-finite" AND abs:binomial'),
    # ---- 追查：上面命中、但 OpenAlex / Crossref 没有摘要的两篇（找预印本版本的摘要）----
    Q("fu01", "追查 Eu-Lee 2026", "Enumeration of pattern-avoiding (0,1)-matrices and their symmetry classes", 'ti:"pattern-avoiding" AND ti:matrices AND ti:symmetry'),
    Q("fu02", "追查 Mu-Welker 2026", "On a question about real-rooted polynomials and f-polynomials of simplicial complexes", 'ti:"real-rooted" AND ti:"simplicial complexes"'),
]

SEEDS = [
    ("bl26_tn_chain", "doi", "10.1016/j.aim.2025.110760"),
    ("bl26_tn_chain_arxiv", "doi", "10.48550/arxiv.2412.06595"),
    ("ak23_chain_partition", "doi", "10.5070/c63160425"),
    ("adk24_two_classes", "doi", "10.37236/12218"),
    ("zhang2016_contraction", "doi", "10.1145/2930889.2930890"),
    ("brenti1989_memoir", "doi", "10.1090/memo/0413"),
    ("stanley1998_graph_colorings", "title", "Graph colorings and related symmetric functions: ideas and applications"),
]

KW = ["chain polynomial", "chain enumeration", "real-rooted", "real roots", "real zeros", "only real", "interlac", "order complex", "h-polynomial",
      "eulerian", "multichain", "zeta polynomial", "boolean lattice", "pattern", "stirling", "annihilat", "ore ", "ideal", "binomial transform",
      "words", "avoid", "log-concav", "sign change"]


def run(args):
    os.makedirs(RAW, exist_ok=True)
    srcs = (args.sources or "openalex,crossref,arxiv").split(",")
    man = open(os.path.join(RAW, "_manifest.jsonl"), "a", encoding="utf-8", newline="\n")
    for q in QUERIES:
        for src in srcs:
            path = os.path.join(RAW, f"{src}__{q['id']}.{LS.EXT[src]}")
            if os.path.exists(path):
                continue
            url = LS.build_url(src, q)
            if not url:
                continue
            data, status = LS.fetch(src, url)
            man.write(json.dumps(dict(t=time.strftime("%Y-%m-%d %H:%M:%S"), src=src, qid=q["id"], status=status, bytes=len(data or b"")), ensure_ascii=False) + "\n")
            man.flush()
            if data is None:
                print(f"[{src} {q['id']}] 失败 {status}", flush=True)
                continue
            open(path, "wb").write(data)
            print(f"[{src} {q['id']}] {len(data)} 字节", flush=True)
    for name, kind, val in SEEDS:
        path = os.path.join(RAW, f"cites__{name}.json")
        if os.path.exists(path):
            continue
        seed = CB.resolve(kind, val)
        if not seed:
            print(f"[cites {name}] 解析失败", flush=True)
            man.write(json.dumps(dict(t=time.strftime("%Y-%m-%d %H:%M:%S"), src="openalex-cites", qid=name, status="unresolved", bytes=0), ensure_ascii=False) + "\n")
            continue
        wid = seed["id"].rsplit("/", 1)[-1]
        works, cursor = [], "*"
        while cursor and len(works) < 1500:
            r = CB.get("https://api.openalex.org/works?" + urllib.parse.urlencode({"filter": "cites:" + wid, "per-page": 200, "select": CB.SEL, "cursor": cursor}))
            if "error" in r:
                print(f"[cites {name}] 出错 {r['error']}", flush=True)
                break
            works += r.get("results", [])
            cursor = (r.get("meta") or {}).get("next_cursor")
            if not r.get("results"):
                break
        json.dump(dict(seed=seed, kind=kind, val=val, n=len(works), works=works), open(path, "w", encoding="utf-8"), ensure_ascii=False)
        man.write(json.dumps(dict(t=time.strftime("%Y-%m-%d %H:%M:%S"), src="openalex-cites", qid=name, status=200, bytes=os.path.getsize(path)), ensure_ascii=False) + "\n")
        print(f"[cites {name}] 种子 = {seed.get('display_name')!r} ({seed.get('publication_year')}), 记录被引 {seed.get('cited_by_count')}, 取回 {len(works)} 篇", flush=True)
    man.close()


def cell(s, n):
    return (s or "").replace("|", "/").replace("\n", " ")[:n]


def report(args):
    out = [f"# 第三次新颖性补查（{time.strftime('%Y-%m-%d %H:%M')} 由 recheck_2026-10-10.py report 生成）\n",
           "只列原始返回里的题名与元数据；分类与结论在 notes/新颖性核查_2026-10-07.md §10。\n",
           "## 查询（每条：OpenAlex 前 20、Crossref 前 15、arXiv 前 20）\n"]
    pool = {}
    for q in QUERIES:
        out.append(f"### {q['id']}（{q['claim']}）：{q['text']}\n")
        out.append("| 来源 | 名次 | 年 | 题名 | 作者 | 出处 | DOI / arXiv |\n|---|---|---|---|---|---|---|")
        for src in ("openalex", "crossref", "arxiv"):
            path = os.path.join(RAW, f"{src}__{q['id']}.{LS.EXT[src]}")
            if not os.path.exists(path):
                out.append(f"| {src} | — | — | （没有原始返回） | | | |")
                continue
            try:
                recs = LS.PARSERS[src](open(path, "rb").read())
            except Exception as e:  # noqa: BLE001
                out.append(f"| {src} | — | — | （解析失败：{cell(str(e), 60)}） | | | |")
                continue
            for r in recs[:10]:
                key = (r["doi"] or r["arxiv"] or r["title"].lower())[:120]
                p = pool.setdefault(key, dict(r, hits=set()))
                p["hits"].add(q["id"])
                au = ", ".join(r["authors"][:3]) + (" 等" if len(r["authors"]) > 3 else "")
                out.append(f"| {src} | {r['rank']} | {r['year']} | {cell(r['title'], 110)} | {cell(au, 50)} | {cell(r['venue'], 36)} | "
                           f"{r['doi'] or ('arXiv:' + r['arxiv'] if r['arxiv'] else cell(r['url'], 50))} |")
        out.append("")
    multi = sorted((p for p in pool.values() if len(p["hits"]) >= 2), key=lambda p: (-len(p["hits"]), -(p["year"] or 0)))
    out.append(f"## 同时命中 ≥2 条查询的文献（{len(multi)} 篇，取每条查询每个来源的前 10）\n")
    out.append("| 命中 | 年 | 题名 | DOI / arXiv |\n|---|---|---|---|")
    for p in multi:
        out.append(f"| {','.join(sorted(p['hits']))} | {p['year']} | {cell(p['title'], 120)} | {p['doi'] or ('arXiv:' + p['arxiv'] if p['arxiv'] else '')} |")
    out.append("")
    out.append("## 前向引用（OpenAlex `cites:`）\n")
    rows, summary = {}, []
    for name, kind, val in SEEDS:
        path = os.path.join(RAW, f"cites__{name}.json")
        if not os.path.exists(path):
            summary.append(f"| {name} | （未取到） | | | |")
            continue
        d = json.load(open(path, encoding="utf-8"))
        s = d["seed"]
        summary.append(f"| {name} | {cell(s.get('display_name'), 80)} | {s.get('publication_year')} | {s.get('cited_by_count')} | {d['n']} |")
        for w in d["works"]:
            ab = CB.inv_abstract(w.get("abstract_inverted_index"))
            text = ((w.get("display_name") or "") + " " + ab).lower()
            p = rows.setdefault(w["id"], dict(title=w.get("display_name") or "", year=w.get("publication_year"), doi=(w.get("doi") or "").replace("https://doi.org/", ""),
                                              id=w["id"], text=text, seeds=set(),
                                              authors=[(a.get("author") or {}).get("display_name", "") for a in w.get("authorships", [])][:3]))
            p["seeds"].add(name)
    out.append("| 种子 | OpenAlex 题名 | 年 | 记录被引 | 取回 |\n|---|---|---|---|---|")
    out += summary
    scored = []
    for p in rows.values():
        kw = [k.strip() for k in KW if k in p["text"]]
        scored.append((len(kw) + 2 * (len(p["seeds"]) - 1), p, kw))
    scored.sort(key=lambda t: (-t[0], -(t[1]["year"] or 0)))
    out.append(f"\n共 {len(scored)} 篇去重引用；下表列关键词得分 ≥ 2 的（得分 = 命中关键词数 + 2 ×（多引一个种子））。\n")
    out.append("| 得分 | 年 | 题名 | 作者 | DOI / OpenAlex | 种子 | 关键词 |\n|---|---|---|---|---|---|---|")
    for sc, p, kw in scored:
        if sc < 2:
            continue
        out.append(f"| {sc} | {p['year']} | {cell(p['title'], 110)} | {cell(', '.join(p['authors']), 50)} | {p['doi'] or p['id']} | "
                   f"{','.join(sorted(p['seeds']))} | {','.join(kw)} |")
    open(REPORT, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print(f"查询 {len(QUERIES)} 条，去重文献 {len(pool)} 篇（前 10 名），前向引用 {len(scored)} 篇；已写 {os.path.relpath(REPORT, ROOT)}")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("run")
    p.add_argument("--sources")
    p.set_defaults(fn=run)
    sub.add_parser("report").set_defaults(fn=report)
    a = ap.parse_args()
    a.fn(a)
