# -*- coding: utf-8 -*-
"""s8-b1 第 2 步：对 notes/05（B1 的证明）做独立的精确核对。真值只取自 code/core.py。

用法：py -3.14 s2_main.py <节>[,<节>...] [K=60] [KA=40] [KB=16] [KAUX=30] [KEXT=0]
节：truth rec base rel aux thm2 hroots newton c3
  truth  N 的真值：U 的高度 DP + 容斥（k<=K），与按定义 DFS（k<=9）对照；N(k,1)=1、N(k,k)=2、N(k,q)>0
  rec    T1.4(2) 三角递推（3<=k<=K）与引理 0：n_k = (1+z)n_{k-1} + Φ n_{k-3}（4<=k<=K）；k=3 的偏差
  base   基例 n_1..n_4、Tn_1、Tn_2、Φn_1、Tn_3 的显式形式与六条基例关系（判定 A、B）
  rel    四条关系 α_k、β_k（2<=k<=KA）、δ_k、ε_k（3<=k<=KA）用判定 A；k<=KB 再用判定 B
  aux    归纳步里用到的每一条中间关系与两条恒等式（3<=k<=KAUX）
  thm2   gcd(n_k,n_{k-1}) = (1+z)^{⌈(k-1)/3⌉-1}；n_k 在 -1 的重数 = ⌈k/3⌉-1；去掉 (1+z) 后无平方因子、全实根、⌊2k/3⌋ 个
  hroots h_k 由 N 直接展开：deg = ⌊2k/3⌋、互异实根个数 = 次数、无平方因子（1<=k<=K；KEXT>K 时用引理 0 生成的 n_k 续到 KEXT）
  newton Newton 不等式与严格对数凹（2<=q<=k-1）
  c3     t 坐标下相邻 h_k、h_{k+1} 两个方向都不交错（2<=k<=12；与表 C 的 C3 对照）
"""
import sys
import time

from px import (trim, deg, lc, add, sub, mul, pw, deriv, mulz, mul1z, T, Phi, ev, pgcd,
                exact_div, is_squarefree, is_real_rooted, sturm_count, mult_neg1,
                interlace_A, interlace_B, ONEZ)
from truth import N_table_from_U, N_brute_rows, nrow

args = sys.argv[1:]
sections = set(args[0].split(',')) if args else {'truth', 'rec', 'base', 'thm2', 'newton', 'c3'}
opts = dict(a.split('=') for a in args[1:])
K = int(opts.get('K', 60))
KA = int(opts.get('KA', 40))
KB = int(opts.get('KB', 16))
KAUX = int(opts.get('KAUX', 30))
KEXT = int(opts.get('KEXT', 0))
VERB = int(opts.get('VERB', 0))

t00 = time.time()
fails = []
npass = 0


def check(name, cond, extra=""):
    global npass
    if cond:
        npass += 1
    else:
        fails.append(name)
        print("FAIL", name, extra, flush=True)


def ceil3(k):
    return -(-k // 3)


print("sections:", sorted(sections), "K=%d KA=%d KB=%d KAUX=%d KEXT=%d" % (K, KA, KB, KAUX, KEXT), flush=True)
t = time.time()
N = N_table_from_U(K)
n = {k: nrow(N, k) for k in range(1, K + 1)}
print("[truth] N table from U (k,q<=%d) in %.1fs" % (K, time.time() - t), flush=True)
KMAX = max(K, KEXT)
for k in range(K + 1, KMAX + 1):
    n[k] = add(mul1z(n[k - 1]), Phi(n[k - 3]))
if KMAX > K:
    print("[ext] n_k for %d<k<=%d generated by Lemma 0 (Lemma 0 itself is checked against the truth "
          "for 4<=k<=%d in section rec)" % (K, KMAX, K), flush=True)

if 'truth' in sections:
    br = N_brute_rows(9)
    for k in range(0, 10):
        for q in range(0, 11):
            check("truth-brute k=%d q=%d" % (k, q), br[k][q] == N[k][q], "%s vs %s" % (br[k][q], N[k][q]))
    for k in range(1, K + 1):
        check("N(k,0)=0 k=%d" % k, N[k][0] == 0)
        check("N(k,1)=1 k=%d" % k, N[k][1] == 1)
        if k >= 2:
            check("N(k,k)=2 k=%d" % k, N[k][k] == 2)
        check("N(k,q)>0 for 1<=q<=k, k=%d" % k, all(N[k][q] > 0 for q in range(1, k + 1)))
        check("N(k,q)=0 for q>k, k=%d" % k, all(N[k][q] == 0 for q in range(k + 1, K + 1)))
        check("deg n_k = k-1, k=%d" % k, deg(n[k]) == k - 1)
    print("[truth] brute (k<=9) and basic facts (k<=%d) done" % K, flush=True)

if 'rec' in sections:
    def NN(k, q):
        if k < 0 or q < 0 or q > K:
            return 0
        return N[k][q]
    for k in range(3, K + 1):
        ok = True
        for q in range(1, K + 1):
            rhs = NN(k - 1, q - 1) + NN(k - 1, q) + (q - 1) * (NN(k - 3, q - 2) + 2 * NN(k - 3, q - 1) + NN(k - 3, q))
            if rhs != N[k][q]:
                ok = False
        check("T1.4(2) k=%d" % k, ok)
    for k in range(4, K + 1):
        rhs = add(mul1z(n[k - 1]), Phi(n[k - 3]))
        check("Lemma0 k=%d" % k, trim(rhs) == trim(n[k]))
    # k=3：没有 n_0，三角递推里 q=2 的 N(0,0)=1 贡献 z
    diff = sub(n[3], mul1z(n[2]))
    print("[rec] k=3: n_3 - (1+z) n_2 =", diff, "(the N(0,0)=1 contribution; Lemma 0 is only claimed for k>=4)")
    print("[rec] T1.4(2) for 3<=k<=%d and Lemma 0 for 4<=k<=%d done" % (K, K), flush=True)

if 'base' in sections:
    print("[base] n_1..n_4:", n[1], n[2], n[3], n[4])
    check("n1", n[1] == [1])
    check("n2", n[2] == [1, 2])
    check("n3", n[3] == [1, 4, 2])
    check("Tn1=2z", T(n[1]) == [0, 2])
    check("Tn2=2z(2+3z)", T(n[2]) == mul([0, 2], [2, 3]))
    check("Phin1=2z(1+z)", Phi(n[1]) == mul([0, 2], [1, 1]))
    check("Tn3=2z(2z+1)(2z+3)", T(n[3]) == mul(mul([0, 2], [1, 2]), [3, 2]))
    check("n4=(1+z)(n3+2z)", n[4] == mul1z(add(n[3], [0, 2])))
    base = [("alpha_2", n[1], n[2]), ("beta_2", n[2], T(n[1])), ("alpha_3", n[2], n[3]),
            ("beta_3", n[3], T(n[2])), ("delta_3", n[3], Phi(n[1])), ("epsilon_3", Phi(n[1]), T(n[3]))]
    for name, g, f in base:
        a, ma = interlace_A(g, f)
        b, mb = interlace_B(g, f)
        check("base " + name, a and b, "A=%s B=%s" % (ma, mb))
    # 注中基例的不等式「√2/2 > 1/2」「-1+√2/2 > -2/3」都由上面六条精确判定覆盖
    print("[base] done", flush=True)

if 'rel' in sections:
    tA = time.time()
    for k in range(2, min(KA, KMAX) + 1):
        t1 = time.time()
        rels = [("alpha_%d" % k, n[k - 1], n[k]), ("beta_%d" % k, n[k], T(n[k - 1]))]
        if k >= 3:
            rels += [("delta_%d" % k, n[k], Phi(n[k - 2])), ("epsilon_%d" % k, Phi(n[k - 2]), T(n[k]))]
        msgs = []
        for name, g, f in rels:
            a, ma = interlace_A(g, f)
            check("relA " + name, a, ma)
            msgs.append("%s:%s" % (name.split('_')[0][:3], "ok" if a else "FAIL"))
            if k <= KB:
                b, mb = interlace_B(g, f)
                check("relB " + name, b, mb)
                check("relA==relB " + name, a == b)
        print("[rel] k=%2d %s%s  %.1fs" % (k, " ".join(msgs), "  (+B)" if k <= KB else "", time.time() - t1), flush=True)
    print("[rel] done in %.1fs" % (time.time() - tA), flush=True)

if 'aux' in sections:
    tA = time.time()
    for k in range(3, min(KAUX, KMAX - 1) + 1):
        A_, B_, C_ = n[k], n[k - 1], n[k - 2]
        TA, TB, TC = T(A_), T(B_), T(C_)
        PhiA, PhiB, PhiC = Phi(A_), Phi(B_), Phi(C_)
        T2C = T(TC)
        nk1 = n[k + 1]
        check("aux k=%d n_{k+1}=(1+z)(A+TC)" % k, nk1 == mul1z(add(A_, TC)))
        terms = [PhiA, mul([0, 1, 1], A_), mul1z(T2C), mul([0, 1, 1], TC)]
        check("aux k=%d T n_{k+1} = 4 terms" % k, T(nk1) == add(*terms))
        check("aux k=%d degrees of 4 terms" % k,
              [deg(x) for x in terms] == [k + 1, k + 1, k, k] and deg(PhiB) == k and deg(T(nk1)) == k + 1)
        rels = [
            ("A<<(1+z)A [L4i]", A_, mul1z(A_)),
            ("A<<PhiC [delta_k]", A_, PhiC),
            ("(1+z)A<<TA [L5iii]", mul1z(A_), TA),
            ("PhiC<<TA [eps_k]", PhiC, TA),
            ("A<<TB [beta_k]", A_, TB),
            ("C<<B [alpha_{k-1}]", C_, B_),
            ("B<<TC [beta_{k-1}]", B_, TC),
            ("TC<<TB [L5ii]", TC, TB),
            ("A+TC<<TB", add(A_, TC), TB),
            ("PhiB<<PhiA [term1]", PhiB, PhiA),
            ("TB<<zA [L4ii]", TB, mulz(A_)),
            ("PhiB<<z(1+z)A [term2]", PhiB, terms[1]),
            ("TB<<T(TC) [L5ii]", TB, T2C),
            ("PhiB<<(1+z)T^2C [term3]", PhiB, terms[2]),
            ("TB<<zTC [L4ii]", TB, mulz(TC)),
            ("PhiB<<z(1+z)TC [term4]", PhiB, terms[3]),
            ("alpha_{k+1}", A_, nk1),
            ("beta_{k+1}", nk1, TA),
            ("delta_{k+1}", nk1, PhiB),
            ("epsilon_{k+1}", PhiB, T(nk1)),
        ]
        bad = []
        for name, g, f in rels:
            if VERB:
                print("   [aux] k=%d %s deg g=%d deg f=%d" % (k, name, deg(g), deg(f)), flush=True)
            a, ma = interlace_A(g, f)
            check("aux k=%d %s" % (k, name), a, ma)
            if not a:
                bad.append(name)
        print("[aux] k=%2d %d relations %s" % (k, len(rels), "all ok" if not bad else "FAIL " + str(bad)), flush=True)
    print("[aux] done in %.1fs" % (time.time() - tA), flush=True)

if 'thm2' in sections:
    tA = time.time()
    for k in range(1, KMAX + 1):
        a_k = ceil3(k) - 1
        m = mult_neg1(n[k])
        check("mult(-1) in n_k = ceil(k/3)-1, k=%d" % k, m == a_k, "got %d" % m)
        r = exact_div(n[k], pw(ONEZ, m))
        check("n_k/(1+z)^a: r(-1)!=0, k=%d" % k, ev(r, -1) != 0)
        check("n_k/(1+z)^a squarefree, k=%d" % k, is_squarefree(r))
        check("n_k/(1+z)^a real-rooted, #roots=floor(2k/3), k=%d" % k,
              sturm_count(r) == deg(r) == (2 * k) // 3)
        check("n_k(0)=1, k=%d" % k, ev(n[k], 0) == 1)
        if k >= 2:
            g = pgcd(n[k], n[k - 1])
            exp = pw(ONEZ, ceil3(k - 1) - 1)
            check("gcd(n_k,n_{k-1}) = (1+z)^{ceil((k-1)/3)-1}, k=%d" % k, g == exp, "gcd=%s" % g)
    print("[thm2] done (k<=%d) in %.1fs" % (KMAX, time.time() - tA), flush=True)


def h_from_N(Nrow, k):
    """h_k(t) = Σ_q N(k,q) t^{q-1} (1-t)^{k-q}，k>=1。"""
    h = []
    for q in range(1, k + 1):
        c = Nrow[q] if q < len(Nrow) else 0
        if c:
            h = add(h, mul([0] * (q - 1) + [c], pw([1, -1], k - q)))
    return h


if 'hroots' in sections:
    tA = time.time()
    for k in range(1, K + 1):
        h = h_from_N(N[k], k)
        d = deg(h)
        ok = (d == (2 * k) // 3) and (sturm_count(h) == d) and is_squarefree(h)
        check("h_k real & distinct, k=%d" % k, ok, "deg %d, sturm %d" % (d, sturm_count(h)))
        if k in (1, 2, 3, 4, 10, 20, 30, 40, 50, 60):
            print("[hroots] k=%2d deg h_k=%2d, distinct real roots=%2d, squarefree=%s, lc=%d" %
                  (k, d, sturm_count(h), is_squarefree(h), lc(h)), flush=True)
    print("[hroots] truth part (k<=%d) done in %.1fs" % (K, time.time() - tA), flush=True)
    if KEXT > K:
        for k in range(K + 1, KEXT + 1):
            Nrow = [0] + list(n[k])
            h = h_from_N(Nrow, k)
            d = deg(h)
            sc = sturm_count(h)
            ok = (d == (2 * k) // 3) and (sc == d) and is_squarefree(h)
            check("h_k real & distinct (recurrence), k=%d" % k, ok, "deg %d sturm %d" % (d, sc))
            if k % 10 == 0:
                print("[hroots-ext] k=%3d deg=%2d distinct real roots=%2d  %.1fs" % (k, d, sc, time.time() - tA), flush=True)
        print("[hroots-ext] (k<=%d via Lemma 0) done in %.1fs" % (KEXT, time.time() - tA), flush=True)

if 'newton' in sections:
    for k in range(3, K + 1):
        ok1 = ok2 = True
        for q in range(2, k):
            a, b, c = N[k][q - 1], N[k][q], N[k][q + 1]
            if not (b * b * (q - 1) * (k - q) >= a * c * q * (k - q + 1)):
                ok1 = False
            if not (b * b > a * c):
                ok2 = False
        check("Newton k=%d" % k, ok1)
        check("strict log-concave k=%d" % k, ok2)
    print("[newton] done (k<=%d)" % K, flush=True)

if 'c3' in sections:
    def pos(p):
        return p if lc(p) > 0 else [-c for c in p]
    for k in range(2, 13):
        hk, hk1 = pos(h_from_N(N[k], k)), pos(h_from_N(N[k + 1], k + 1))
        f1 = interlace_A(hk, hk1)[0] or interlace_A(hk1, hk)[0]
        f2 = interlace_B(hk, hk1)[0] or interlace_B(hk1, hk)[0]
        check("C3 (t-coords not interlacing) k=%d" % k, (not f1) and (not f2))
        check("z-coords alpha_{k+1} k=%d" % k, interlace_A(n[k], n[k + 1])[0])
    print("[c3] done", flush=True)

print("TOTAL: %d checks passed, %d failed; %.1fs" % (npass, len(fails), time.time() - t00), flush=True)
sys.exit(1 if fails else 0)
